local io = require('io')
print("olá bem vindo ao manipulador csv")
print("Digite seu nome")
nome = io.read()
print("Digite seu sua idade")
idade = io.read()
print("Digite sua altura")
altura = io.read()

csv = io.open("pessoa.csv", "w")
csv:write("nome,idade,altura\n")
csv:write(nome..','..idade..','..altura..'\n')
csv:flush()
csv:close()
print("arquivo csv gerado com sucesso")